### ISSUE TITLE
Linux versions, 3.x

### ISSUE THREAD

**Issue by synic** [roastworld/roast-time#3]
I saw that linux isn't listed on the downloads page, and the releases for linux lag behind windows and OS X. Is linux support being dropped?

**Comment by jacoblilsys** [comment]
https://github.com/roastworld/roast-time/releases
v2.5.5-stable is the latest version for all platforms. Please don't use any V3 internal builds as they could corrupt your database and are for internal testing.
Linux support is not being dropped.

**Comment by synic** [comment]
Where is the best place to get support for the Linux version?

I downloaded 2.5.5, but it won't connect to the roaster. I am using Ubuntu 20, have added the appropriate udev rules. Added my user to the dialout group (and relogged). I see the STMicroelectronics and device information in `dmesg`. `/dev/ttyACM0` has the right permissions. Still don't connect. I thought maybe 2.5.5 was too old or something.

**Comment by jacoblilsys** [comment]
The best way is going to the official forum for the bullet. 
There are a few threads about Linux and USB connection like this one: https://community.roast.world/t/roaster-not-connected-linux/2765/5
If you are still having problems then please submit a ticket on aillio.com

**Comment by synic** [comment]
Ah, sweet. I signed up. That post helped me get it working, and I added some new information on how to get it to work without administrator. 

Thanks for your help!
