### ISSUE TITLE
Login (email not recognized)

### ISSUE THREAD

**Issue by trevor-scheer** [roastworld/roast-time#5]
Hello,

For some reason I'm unable to login using my account on a new device. I get this error:
>Email not found or invalid password.

It also doesn't recognize my account as even existing when I try to password reset. I see this error:
>We couldn't find your account with that information.

I've successfully logged into the roast.world web app on both devices. I've also successfully logged out and back into the app on my old device.

Probably worth mentioning: the new device is an M1 Mac. The M1s have issues compiling anything but newer versions of node unless run with Rosetta, so my system's node version is 16.4.2.

Let me know if there are known issues or if I can provide you with more info.

Thanks in advance!

**Comment by jacoblilsys** [comment]
Hi Trevor,

Where did you try to reset the password?
Could you try this link below?
https://roast.world/reset-password
Otherwise please send an email to support@aillio.com (including the email you used to sign in)

**Comment by trevor-scheer** [comment]
Hi @jacoblilsys, I'm fairly convinced this is a device problem and not a password/account problem. I'll paste what I sent to the support email address, but I think this requires software level support rather than account support. Note that I've taken steps to confirm the account is still working fine on my old laptop, even after a password reset.

> Hi,
> My account seems to be having some trouble with passwords and identity. I've been operating under the impression that the Aillio ID for RoastTime and my login for roast.world are the same.
> 
> Here is my "journey" so far:
> 1. Try to login to RoastTime on a new laptop. The app tells me my credentials are incorrect.
> 2. Try to reset password within RoastTime. The app tells me my account doesn't exist. (still on new laptop)
> 3. Confirm my account exists by logging out and back in to RoastTime on my old laptop.
> 4. Reset my password via https://roast.world/reset-password
> 5. Same result on new laptop (can't login to RoastTime, email unknown on RoastTime)
> 6. Logout and log back in using new password on old laptop, no problem.
> 
> I think this is an issue with my new laptop. It's an M1 Macbook Pro. I opened a GitHub issue here:
> https://github.com/roastworld/roast-time/issues/5
> I left a note in the community here:
> https://community.roast.world/t/rt-and-macos-big-sur-m1-macs/3756/12?u=trevor.scheer0arg

Is there a way for me to obtain logs from RoastTime? I'd bet there's a network error happening on the new laptop and it happens to be "revealing itself" as invalid credentials.

**Comment by trevor-scheer** [comment]
Resolved - discovered there's a RoastTime v3. Not sure if I had it right on my old machine but this is working for me now.
